#js 
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
  labels:
    app: myapplication
data:
  appUrl: "http://my-app-server"
  timeout: "30"
---
apiVersion: v1
kind: Pod
metadata:
  name: "mypod"
  namespace: default
  labels:
    app: "myapp"
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    env:
    - name: "request.timeout"
      valueFrom:
        configMapKeyRef:
          name: app-properties
          key: timeout
    - name: "application.url"
      valueFrom:
        configMapKeyRef:
          name: app-properties
          key: appUrl
    args:
    - env