#js 
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
  labels:
    app: myapplication
data:
  appUrl: "http://my-app-server"
  timeout: "30"
---
apiVersion: v1
kind: Pod
metadata:
  name: "mypod-nginx"
  namespace: default
  labels:
    app: "myapp"
spec:
  #restartPolicy: Never
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef: #secretRef for Secrets 
        name: app-properties
    args:
    - env